### ISSUE TITLE
[1.0.2] Crash

### ISSUE THREAD

**Issue by Khytwel** [yurisuika/Blossom#2]
Hi,

I have a crash during the generation of a new world or the loading of chunks. I noticed that I had a similar crash with a player in the CurseForge comments (his crash report: https://github.com/2Devic/projects/blob/main/crash-2022-02-13_21.36.36-server.txt)

Here is my crash report: https://gist.github.com/Khytwel/f2bdbcde277a30635301d987124c49d5. Knowing that since I deactivated the mod, I have no more problems after generating several new worlds and joining old worlds affected by the crash.

**Comment by yurisuika** [comment]
Thanks for the report.

As I was asking from that dude, it would be a big help if you could try to narrow it down to where the conflict lies. Since you as well have quite a few mods, this would really help speed up the process, as I'd have to first find and download and learn about what all the mods do to figure out which actually.

I have a feeling that I might be able to fix it, albeit while producing suboptimal results of compatibility in other regards. I will append a file if you wish to test it out.

**Comment by yurisuika** [comment]
Well apparently I cannot add jars to comments here, so I just made a quick release.
https://github.com/yurisuika/Blossom/releases/tag/1.0.3
This changes it so that instead of the change I made that makes LeavesBlock (and FloweringLeavesBlock) test for blocks in the LEAVES tag when updating distance from logs, it restores the test as in vanilla for explicitly testing for LeavesBlock (and FloweringLeavesBlock). My idea was to improve compatibility with other mods that have leaves that use custom classes but still are in the tags, but for some reason it is trying to deal with distance with saplings, and that just seems like there is some mod that screws around with them, probably adding them to the LEAVES tag.

**Comment by yurisuika** [comment]
In the meantime I have compiled a list of the mods that both of you use, hopefully the one causing the incompatibility is in that list to find.

**Comment by yurisuika** [comment]
AH! I knew it, I knew it, I knew it! So, one more mod comes into conflict with Terralith. Yeah, that is the culprit, I had a feeling. Yes, indeed Terralith adds saplings to the leaves tag.

**Comment by yurisuika** [comment]
I'll get a workaround out for this soon. I will in turn also remove all my additions of leaves to the flowers tags so I will not break other mods myself and instead just inject the leaves into the bee searching for flowers.

I am not gonna test it with Terralith, but I pretty positive these changes will make it compatible.
