### ISSUE TITLE
Blossom Crash at setting property 1.19.2 Dedicated Server

### ISSUE THREAD

**Issue by arazadaz** [yurisuika/Blossom#7]
Crash log: https://mclo.gs/eJIIjXr

This only happens in the latest version. It doesn't happen in the prior versions.

**Comment by yurisuika** [comment]
It looks to be a conflict with another mod "steves_vanilla".

I will look deeper into this soon!

**Comment by palapapa** [comment]
Same problem. Removing Steve's Vanilla doesn't help.

**Comment by yurisuika** [comment]
This is what I am seeing, that it is something that attempts to place a `snowy` state for leaves.

```
Caused by: java.lang.IllegalArgumentException: Cannot set property class_2746{name=snowy, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:air}
--
1829 | at net.minecraft.state.State.with(State.java:117)
1830 | at net.minecraft.block.LeavesBlock.handler$kac001$steves_vanilla$constructor(LeavesBlock.java:3535)
1831 | at net.minecraft.block.LeavesBlock.<init>(LeavesBlock.java:35)
1832 | at dev.yurisuika.blossom.block.FloweringLeavesBlock.<init>(FloweringLeavesBlock.java:46)
1833 | at dev.yurisuika.blossom.Blossom.<clinit>(Blossom.java:105)
1834 | ... 17 more
```

Perhaps you know which mod this may be then?

**Comment by arazadaz** [comment]
I got two ideas. Fabric seasons or immersive weathering maybe?

**Comment by yurisuika** [comment]
Okay, well it turns out that I was testing using the Forge version 0.5.0 by accident of Steve's Vanilla. I thought I had gotten the Fabric version, but I guess not.

I see that for some reason the author has removed all Fabric versions visible from Curseforge, but I was still able to download version 2.0.1 (the one from your crash log) via this URL: https://www.curseforge.com/minecraft/mc-mods/steves-vanilla-fabric/files/3957420

With only FAPI, Blossom, and Steve's, it produces that crash.

This mod is closed source, but I decompiled it to find that it does indeed add a snowy state to leaves via a mixin. These flowering leaves are an extension of vanilla leaves, and that is where it probably goes all haywire. I don't know why it is trying to apply it to air, though. I see this crashes before the game even loads up, so its not something like a block was decaying into air or something like that.

I don't even see any use for this state, either. It only seems to add the state and doesn't do anything with it.

Being as the author has rescinded the entire fabric version (and I cannot say when this happened, but this version of it was released back in August), for now I think it is safe to say any attempts to add some sort of compatibility should wait until whatever is going on with it comes to fruition. At the same time, something as breaking as adding a state to a vanilla block is probably not something that I can (at least personally) figure out how to add compatibility for.

For now I think it is best to leave it to that. But it 100% is that mod which conflicts. You just have to choose which one to use. It does add a pretty cool creature, I will say.

**Comment by palapapa** [comment]
I didn't correctly delete Steve's Vanilla. After deleting it the mod does work.

**Comment by arazadaz** [comment]
I see. Well seeing as the original mod removed the fabric version. I'll assume that means he is no longer supporting fabric. I'll take it out of my pack for now. Thanks.

**Comment by arazadaz** [comment]
I found this is actually incompatible with other mods as well. Strangely, it only affects Dedicated servers. Create is another mod that throws a crash report related to this though.

**Comment by yurisuika** [comment]
Which mod are you talking about?

I have not been able to reproduce a crash on a dedicated server with latest Forge and Create with Blossom for 1.19.2.

If you have something of concern, please provide logs and details.

**Comment by arazadaz** [comment]
Sorry, I should specify, this is the fabric version of the mod. I have over 300 mods in my pack, but the crash report was mentioning create. I had all of the create addons, so it may have been an addon. I deleted the report, but if you'd like I can give you the modpack once it's uploaded on CF for your own testing.

**Comment by yurisuika** [comment]
I have tested both locally and on dedicated servers, there is no crash with latest versions Create 0.5.1 Forge or 0.5.0 Fabric port with Blossom on 1.19.2.

Create 0.5.0i patch 6 port for Fabric specifically looks to just be broken on its own, but that has nothing to do with Blossom.

If you do not provide a full log then I have nothing to go on.

**Comment by arazadaz** [comment]
I'll get a report real quick. There's over 300 mods. It could be any. I can
give you the modpack to once it's up on cf.

**Comment by arazadaz** [comment]
Ok, I can't seem to reproduce the crash report currently, so I'll mark this as closed again for now. If it happens again. I'll grab the report and send it your way.
